-- MySQL Script generated by MySQL Workbench
-- Mon Dec  5 16:28:39 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`productos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `precio` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre de la categoria` VARCHAR(45) NOT NULL,
  `precio` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`perfil` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `perfil` VARCHAR(45) NOT NULL,
  `perfil_id` INT NOT NULL,
  PRIMARY KEY (`id`, `perfil_id`),
  INDEX `fk_Usuarios_perfil1_idx` (`perfil_id` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_perfil1`
    FOREIGN KEY (`perfil_id`)
    REFERENCES `mydb`.`perfil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sistemas_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sistemas_pago` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Orden` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL,
  `Usuarios_id` INT NOT NULL,
  `sistemas_pago_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Orden_Usuarios1_idx` (`Usuarios_id` ASC) VISIBLE,
  INDEX `fk_Orden_sistemas_pago1_idx` (`sistemas_pago_id` ASC) VISIBLE,
  CONSTRAINT `fk_Orden_Usuarios1`
    FOREIGN KEY (`Usuarios_id`)
    REFERENCES `mydb`.`Usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orden_sistemas_pago1`
    FOREIGN KEY (`sistemas_pago_id`)
    REFERENCES `mydb`.`sistemas_pago` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`productos_has_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`productos_has_categorias` (
  `productos_id` INT UNSIGNED NOT NULL,
  `categorias_id` INT NOT NULL,
  PRIMARY KEY (`productos_id`, `categorias_id`),
  INDEX `fk_productos_has_categorias_categorias1_idx` (`categorias_id` ASC) VISIBLE,
  INDEX `fk_productos_has_categorias_productos1_idx` (`productos_id` ASC) VISIBLE,
  CONSTRAINT `fk_productos_has_categorias_productos1`
    FOREIGN KEY (`productos_id`)
    REFERENCES `mydb`.`productos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_productos_has_categorias_categorias1`
    FOREIGN KEY (`categorias_id`)
    REFERENCES `mydb`.`categorias` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`productos_has_Orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`productos_has_Orden` (
  `productos_id` INT UNSIGNED NOT NULL,
  `Orden_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`, `productos_id`, `Orden_id`),
  INDEX `fk_productos_has_Orden_Orden1_idx` (`Orden_id` ASC) VISIBLE,
  INDEX `fk_productos_has_Orden_productos1_idx` (`productos_id` ASC) VISIBLE,
  CONSTRAINT `fk_productos_has_Orden_productos1`
    FOREIGN KEY (`productos_id`)
    REFERENCES `mydb`.`productos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_productos_has_Orden_Orden1`
    FOREIGN KEY (`Orden_id`)
    REFERENCES `mydb`.`Orden` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lugar_orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lugar_orden` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ciudad` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `Orden_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lugar_orden_Orden1_idx` (`Orden_id` ASC) VISIBLE,
  CONSTRAINT `fk_lugar_orden_Orden1`
    FOREIGN KEY (`Orden_id`)
    REFERENCES `mydb`.`Orden` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
